"""Postgres/pgvector storage helpers for Vercel Marketplace databases.

The local backend remains the default. When ``STORAGE_BACKEND=postgres`` this
package provides the durable stores that replace the markdown/sqlite files
under ``memory/`` with Neon Postgres tables, while preserving the public
store/index APIs used by the rest of the assistant.

One submodule per domain, mirroring the sqlite stores; :mod:`.core` holds the
shared pool/schema plumbing. Everything callers use is re-exported here, so
the split away from the old single module changed no import site — and tests
monkeypatch these package attributes, which every caller (including the
ledger drivers' ``getattr``) resolves at call time.
"""

from __future__ import annotations

from .calendar import (
    caldav_outbox_clear,
    caldav_outbox_enqueue,
    caldav_outbox_pending,
    create_event,
    delete_event,
    ensure_calendar_schema,
    find_by_href,
    get_event,
    list_events,
    restore_event,
    set_caldav_meta,
    update_event,
)
from .core import connect, enabled, require_url, vector_literal
from .docs import (
    add_document,
    delete_document,
    docs_meta_get,
    docs_meta_set,
    ensure_docs_schema,
    get_document,
    list_documents,
    reindex_docs,
    reindex_documents,
    search_chunks,
)
from .expenses import (
    delete_expense_entry,
    ensure_expenses_schema,
    get_expense_entry,
    list_expense_entries,
    log_expense_entry,
)
from .followups import (
    add_followup,
    cancel_followup,
    claim_due_followups,
    ensure_followups_schema,
    list_open_followups,
    update_followup,
)
from .goals import (
    add_goal,
    close_goal,
    ensure_goals_schema,
    list_open_goals,
    update_goal,
)
from .graph import (
    ensure_graph_schema,
    graph_list_edges,
    graph_neighbors,
    graph_note_names,
    graph_resolve,
    prune_graph_orphans,
    reindex_graph,
    remove_graph_note,
    sync_graph_note,
)
from .habits import (
    delete_habit_entry,
    ensure_habits_schema,
    get_habit_entry,
    list_habit_entries,
    log_habit_entry,
)
from .kv import ensure_kv_schema, kv_clear, kv_get, kv_set
from .ledgers import (
    calendar_write_rows,
    claim_calendar_reminders,
    claim_fired,
    claim_task_reminders,
    ensure_fired_schema,
    mark_calendar_writes_undone,
    mark_person_writes_undone,
    mark_task_writes_undone,
    person_write_rows,
    record_calendar_write,
    record_person_write,
    record_task_write,
    task_write_rows,
)
from .lists import (
    create_list_item,
    delete_list_item,
    ensure_lists_schema,
    get_list_item,
    list_list_items,
    set_list_item_done,
)
from .mail import ensure_mail_schema, mail_audit_rows, record_mail_audit
from .memory import (
    bump_recall,
    bump_turn_counter,
    delete_note,
    ensure_memory_schema,
    find_note,
    get_stats,
    list_memory_entries,
    list_notes,
    memory_index_is_empty,
    meta_get,
    meta_set,
    prune_trash,
    purge_stale_files,
    read_index,
    regenerate_index,
    reindex_memory,
    remove_memory_index,
    search_memory_index,
    set_salience,
    unique_name,
    upsert_memory_index,
    virtual_note_path,
    write_note,
)
from .mutes import clear_mute, ensure_mutes_schema, list_mutes, set_mute
from .people import (
    create_person,
    delete_person,
    ensure_people_schema,
    get_person,
    list_people,
    restore_person,
    update_person,
)
from .pushlog import ensure_push_log_schema, recent_push_log, record_push_log
from .reading import (
    create_reading_item,
    delete_reading_item,
    ensure_reading_schema,
    get_reading_item,
    list_reading_items,
    mark_reading_read,
    update_reading_item,
)
from .subscriptions import (
    create_subscription,
    delete_subscription,
    ensure_subscriptions_schema,
    get_subscription,
    list_subscriptions,
    update_subscription,
)
from .tasks import (
    complete_task,
    create_task,
    delete_task,
    ensure_tasks_schema,
    get_task,
    list_tasks,
    restore_task,
    update_task,
)
from .telegram import ensure_telegram_schema, pair_telegram_chat, paired_telegram_chats
from .threads import ensure_threads_schema, known_threads, touch_thread
from .trips import (
    create_trip,
    delete_trip,
    ensure_trips_schema,
    get_trip,
    list_trips,
    update_trip,
)
from .watches import (
    add_watch,
    cancel_watch,
    claim_watch,
    ensure_watches_schema,
    list_active_watches,
)

__all__ = [
    "add_document",
    "add_followup",
    "add_goal",
    "add_watch",
    "bump_recall",
    "bump_turn_counter",
    "caldav_outbox_clear",
    "caldav_outbox_enqueue",
    "caldav_outbox_pending",
    "calendar_write_rows",
    "cancel_followup",
    "cancel_watch",
    "claim_calendar_reminders",
    "claim_due_followups",
    "claim_fired",
    "claim_task_reminders",
    "claim_watch",
    "clear_mute",
    "close_goal",
    "complete_task",
    "connect",
    "create_event",
    "create_list_item",
    "create_person",
    "create_reading_item",
    "create_subscription",
    "create_task",
    "create_trip",
    "delete_document",
    "delete_event",
    "delete_expense_entry",
    "delete_habit_entry",
    "delete_list_item",
    "delete_note",
    "delete_person",
    "delete_reading_item",
    "delete_subscription",
    "delete_task",
    "delete_trip",
    "docs_meta_get",
    "docs_meta_set",
    "enabled",
    "ensure_calendar_schema",
    "ensure_docs_schema",
    "ensure_expenses_schema",
    "ensure_fired_schema",
    "ensure_followups_schema",
    "ensure_goals_schema",
    "ensure_graph_schema",
    "ensure_habits_schema",
    "ensure_kv_schema",
    "ensure_lists_schema",
    "ensure_mail_schema",
    "ensure_memory_schema",
    "ensure_mutes_schema",
    "ensure_people_schema",
    "ensure_push_log_schema",
    "ensure_reading_schema",
    "ensure_subscriptions_schema",
    "ensure_tasks_schema",
    "ensure_telegram_schema",
    "ensure_threads_schema",
    "ensure_trips_schema",
    "ensure_watches_schema",
    "find_by_href",
    "find_note",
    "get_document",
    "get_event",
    "get_expense_entry",
    "get_habit_entry",
    "get_list_item",
    "get_person",
    "get_reading_item",
    "get_stats",
    "get_subscription",
    "get_task",
    "get_trip",
    "graph_list_edges",
    "graph_neighbors",
    "graph_note_names",
    "graph_resolve",
    "known_threads",
    "kv_clear",
    "kv_get",
    "kv_set",
    "list_active_watches",
    "list_documents",
    "list_events",
    "list_expense_entries",
    "list_habit_entries",
    "list_list_items",
    "list_memory_entries",
    "list_mutes",
    "list_notes",
    "list_open_followups",
    "list_open_goals",
    "list_people",
    "list_reading_items",
    "list_subscriptions",
    "list_tasks",
    "list_trips",
    "log_expense_entry",
    "log_habit_entry",
    "mail_audit_rows",
    "mark_calendar_writes_undone",
    "mark_person_writes_undone",
    "mark_reading_read",
    "mark_task_writes_undone",
    "memory_index_is_empty",
    "meta_get",
    "meta_set",
    "pair_telegram_chat",
    "paired_telegram_chats",
    "person_write_rows",
    "prune_graph_orphans",
    "prune_trash",
    "purge_stale_files",
    "read_index",
    "recent_push_log",
    "record_calendar_write",
    "record_mail_audit",
    "record_person_write",
    "record_push_log",
    "record_task_write",
    "regenerate_index",
    "reindex_docs",
    "reindex_documents",
    "reindex_graph",
    "reindex_memory",
    "remove_graph_note",
    "remove_memory_index",
    "require_url",
    "restore_event",
    "restore_person",
    "restore_task",
    "search_chunks",
    "search_memory_index",
    "set_caldav_meta",
    "set_list_item_done",
    "set_mute",
    "set_salience",
    "sync_graph_note",
    "task_write_rows",
    "touch_thread",
    "unique_name",
    "update_event",
    "update_followup",
    "update_goal",
    "update_person",
    "update_reading_item",
    "update_subscription",
    "update_task",
    "update_trip",
    "upsert_memory_index",
    "vector_literal",
    "virtual_note_path",
    "write_note",
]
